### ISSUE TITLE
change data-speed on nested data-scene?

### ISSUE THREAD

**Issue by sbtly** [mickaelchanrion/rolly#8]
I have component like this,
```
const Comp = () => {
  return (
    <section data-scene>
      <div className="rect" />
      <span className="span" data-speed="2">
        Hello CodeSandbox
        <br />
        Start editing to see some magic happen!
      </span>
    </section>
  );
};
```

and I want to set everything else's data-speed to default, and only `span`'s data-speed to '2'.
But it seems like only div that has `data-scene` get to set `data-speed`,
and if `data-scene` get nested, it behaves weirdly.

In the future, I want to set different `translate3d` effect to each div inside the `data-scene` div also.

How can I achieve this?

I made codesandbox for better understanding.
https://codesandbox.io/s/reverent-joliot-gewsi?fontsize=14&hidenavigation=1&theme=dark

**Comment by mickaelchanrion** [comment]
You can't nest scenes and by default, `data-speed` is only evaluated on a scene itself, not the DOM children. This is not mentioned in the documentation, I should update it.

Why not doing this?
```html
<section>
  <div className="rect"  data-scene/>
  <span className="span"  data-scene data-speed="2">
    Hello CodeSandbox
    <br />
    Start editing to see some magic happen!
  </span>
</section>
```
If for some reason, you have to make the whole section moving (because of a colored background for example), there's another solution but it requires more work (implementation of a custom behavior for this type of scene)

**Comment by sbtly** [comment]
I thought maybe there's a way to nest data-scene but apparently not!
Thank you for the explanation 😊

**Comment by mickaelchanrion** [comment]
You're welcome!
Soon, I will create an example of nested scenes using custom scenes. But there are some limitations
